app:
  server:
    port: 8080
  
database:
  host: db
  port: 5433
  user: postgres
  password: 123456
  dbname: geminidb
  sslmode: disable
  timezone: America/Sao_Paulo
  
gemini:
  api_key: AIzaSyCBydeEwc2CUpi2SJ4Lu2gelqRe69aGCNs