app:
  server:
    port: 8080
  
database:
  host: localhost
  port: 5433
  user: postgres
  password: 123456
  dbname: geminidb
  sslmode: disable
  timezone: America/Sao_Paulo
  
gemini:
  api_key: AIzaSyBW9H5CHX2IZXWFxoSe3HK-31jPpoxre7g 