version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: geminidb
    networks:
      - minha_rede

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: geminidb
    networks:
      - minha_rede

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - db
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge