app:
  server:
    port: 8080
  
database:
  host: localhost
  port: 5434 
  user: postgres
  password: 123456
  dbname: geminidb
  sslmode: disable
  timezone: America/Sao_Paulo

gemini:
  api_key: AIzaSyAvyhRX_7y3uYazNp9nK9qu-xPin8ehh2U